<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>_123Vendas.Domain.Sales.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\123Vendas.Domain.Sales.Domain\123Vendas.Domain.Sales.Domain.csproj" />
  </ItemGroup>

</Project>
